#!/usr/bin/env python
# Script d'entrée pour Daznode CLI

import sys
import os

# Ajouter le répertoire parent au chemin
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from cli import cli

if __name__ == '__main__':
    cli() 